Repository swkoubou/HackU2021, pull requests merged in 2021-08, with the labels that each got.

#8 Common/3 READMEにプルリクまでの流れを各く
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: common

#6 vueでfrontの雛形を作った
  .gitignore
  front/README.md
  front/babel.config.js
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/src/App.vue
  front/src/assets/logo.png
  front/src/components/HelloWorld.vue
  front/src/main.js
  front/src/router/index.js
  front/src/store/index.js
  front/src/views/About.vue
  front/src/views/Home.vue
  front/yarn.lock
Labels: front

#17 Update README.md
  README.md
Labels: common

#18 Common/10 ER図の管理をgithubでやめる
  diagram/classDiagram.drawio
  diagram/erDiagram.drawio
  diagram/sequenceDiagram.drawio
Labels: common

#13 問題のコンポーネントを作成しましたFront/5
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docker-compose.yml
  front/README.md
  front/babel.config.js
  front/package-lock.json
  front/public/index.html
  front/src/App.vue
  front/src/components/HelloWorld.vue
  front/src/components/Question.vue
  front/src/components/Question4taku.vue
  front/src/components/QuestionAnaume.vue
  front/src/router/index.js
  front/src/testdata/question.json
  front/src/views/About.vue
  front/src/views/ComponentsPreviewPage.vue
  front/src/views/Home.vue
  front/yarn.lock
  go/go.mod
  nginx/src/index.html
Labels: front

#20 yarn lint した
  front/src/App.vue
  front/src/components/HelloWorld.vue
  front/src/components/Question.vue
  front/src/components/Question4taku.vue
  front/src/components/QuestionAnaume.vue
  front/src/views/About.vue
  front/src/views/ComponentsPreviewPage.vue
  front/src/views/Home.vue
Labels: front

#22 question構造体を作成した
  go/go.mod
  go/go.sum
  go/question/question.go
Labels: back

#25 Collection構造体の中身きめた
  go/collection/collection.go
Labels: back

#27 userを切り出した
  go/account/account.go
  go/collection/collection.go
  go/question/question.go
Labels: back
